# Generated by Django 5.1.1 on 2024-09-14 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('produce_year', models.IntegerField()),
                ('motor_horsepower', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('new', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sell/images/')),
                ('amount', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, max_length=10)),
            ],
        ),
    ]
