# Generated by Django 5.1.1 on 2024-09-14 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_alter_vehicles_amount_alter_vehicles_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicles',
            old_name='motor_horsepower',
            new_name='horsepower',
        ),
    ]
