# Generated by Django 5.1.1 on 2024-09-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_rename_motor_horsepower_vehicles_horsepower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicles',
            old_name='uuid',
            new_name='id',
        ),
    ]
