# Generated by Django 5.1.1 on 2024-09-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_alter_vehicles_amount_alter_vehicles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='description',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
