# Generated by Django 5.1.1 on 2024-09-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0007_alter_vehicles_description_alter_vehicles_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='description',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
    ]
