# Generated by Django 5.1.1 on 2024-09-20 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0010_alter_vehicles_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicles',
            options={'permissions': [('can_view', 'Can_View'), ('can_add', 'Can_Add'), ('can_edit', 'Can_Edit'), ('can_delete', 'Can_Delete')]},
        ),
    ]
