# Generated by Django 5.1.1 on 2024-09-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0012_rename_order_time_vehicles_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
