# Generated by Django 5.1.1 on 2024-09-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0013_alter_vehicles_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
