# Generated by Django 5.1.1 on 2024-09-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0014_alter_vehicles_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicles',
            options={'permissions': [('vehicle_detail', 'You Can view Vehicles'), ('update_vehicle', 'You Can edit Vehicles'), ('delete_vehicle', 'You Can delete Vehicles')]},
        ),
    ]
