# Generated by Django 5.1.1 on 2024-09-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0015_alter_vehicles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicles',
            options={'permissions': [('vehicle_detail', 'You Can view Items'), ('create_vehicle', 'You Can Create Items'), ('update_vehicle', 'You Can edit Items'), ('delete_vehicle', 'You Can delete Items')]},
        ),
    ]
