# Generated by Django 5.1.1 on 2024-12-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0016_alter_vehicles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sell/images/'),
        ),
    ]
